name: Unit tests
on: push

env:
  UV_LOCKED: true # Assert that uv.lock stays unchanged

jobs:
  unit-tests:
    name: Unit tests
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:12.7-alpine
        env:
          POSTGRES_PASSWORD: shop
          POSTGRES_USER: shop
          POSTGRES_DB: shop-test
        ports:
          - 5432:5432
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Install uv and set the python version
        uses: astral-sh/setup-uv@v5
        with:
          version: "0.11.19"
          python-version: "3.11"

      - name: Install dependencies
        run: uv sync --dev

      - name: Run Unit tests
        run: uv run pytest --cov-branch --cov=server tests/unit_tests
        env:
          DATABASE_URI: postgresql://shop:shop@localhost/shop-test
