name: Linting tests
on: push

env:
  UV_LOCKED: true # Assert that uv.lock stays unchanged

jobs:
  lint:
    name: Linting Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install uv and set the python version
        uses: astral-sh/setup-uv@v5
        with:
          version: "0.11.19"
          python-version: "3.11"

      - name: Install dev dependencies
        run: uv sync --dev

      - name: ruff check
        run: uv run ruff check --output-format=github .

      - name: ruff format
        run: uv run ruff format --check .
